import type { HotelProps } from "types/hotel";

export const hotels: HotelProps[] = [
  {
    id: "four-seasons-abu-dhabi-at-al-maryah-island",
    name: "Four Seasons Hotel Abu Dhabi at Al Maryah Island",
    area: "Al Maryah Island",
    rating: { booking: 9.2, google: 4.7 },
    stars: 5,
    price: 5483,
    link: "https://www.booking.com/hotel/ae/four-seasons-abu-dhabi-at-al-maryah-island.html",
    room: {
      title: "Superior King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "the-wb-abu-dhabi-curio-collection-by-hilton",
    name: "The WB Abu Dhabi, Curio Collection By Hilton",
    area: "Yas Island",
    rating: { booking: 9.2, google: 4.7 },
    stars: 5,
    price: 9577,
    link: "https://www.booking.com/hotel/ae/the-wb-abu-dhabi-curio-collection-by-hilton.html",
    room: {
      title: "Superior King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "the-wb-abu-dhabi-curio-collection-by-hilton",
    name: "Park Rotana Abu Dhabi",
    rating: { booking: 9.1, google: 4.6 },
    stars: 5,
    price: 3523,
    link: "https://www.booking.com/hotel/ae/park-rotana-abu-dhabi.html",
    room: {
      title: "Guest Room - King Bed",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "rosewood-abu-dhabi",
    name: "Rosewood Abu Dhabi",
    area: "Al Maryah Island",
    rating: { booking: 9.1, google: 4.6 },
    stars: 5,
    price: 4615,
    link: "https://www.booking.com/hotel/ae/rosewood-abu-dhabi.html",
    room: {
      title: "Deluxe King Room - City View",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "royal-rose-abu-dhabi",
    name: "Royal Rose Hotel Abu Dhabi, Curio Collection by Hilton",
    area: "Downtown Abu Dhabi",
    rating: { booking: 8.9, google: 4.4 },
    stars: 5,
    price: 2392,
    link: "https://www.booking.com/hotel/ae/royal-rose-abu-dhabi.html",
    room: {
      title: "Twin Room",
      sharing: true,
      bed: {
        total: 2,
        type: "Twin",
      },
    },
    breakfast: false,
  },
  {
    id: "grand-hyatt-abu-dhabi-and-residences-emirates-pearl",
    name: "Grand Hyatt Abu Dhabi Hotel & Residences Emirates Pearl",
    rating: { booking: 8.9, google: 4.6 },
    stars: 5,
    price: 3116,
    link: "https://www.booking.com/hotel/ae/grand-hyatt-abu-dhabi-and-residences-emirates-pearl.html",
    room: {
      title: "King Room with Balcony",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "shangri-la-qaryat-al-beri",
    name: "Shangri-La Qaryat Al Beri, Abu Dhabi",
    rating: { booking: 8.9, google: 4.6 },
    stars: 5,
    price: 3258,
    link: "https://www.booking.com/hotel/ae/shangri-la-qaryat-al-beri.html",
    room: {
      title: "Deluxe King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "rixos-marina-abu-dhabi",
    name: "Rixos Marina Abu Dhabi",
    rating: { booking: 8.9, google: 4.8 },
    stars: 5,
    price: 4018,
    link: "https://www.booking.com/hotel/ae/rixos-marina-abu-dhabi.html",
    room: {
      title: "Superior Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
    note: "Private Beach.",
  },
  {
    id: "dusit-thani-abu-dhabi",
    name: "Dusit Thani Abu Dhabi",
    rating: { booking: 8.8, google: 4.5 },
    stars: 5,
    price: 2655,
    link: "https://www.booking.com/hotel/ae/dusit-thani-abu-dhabi.html",
    room: {
      title: "Deluxe Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "hyatt-capital-gate",
    name: "Andaz Capital Gate Abu Dhabi, By Hyatt",
    rating: { booking: 8.8, google: 4.5 },
    stars: 5,
    price: 4072,
    link: "https://www.booking.com/hotel/ae/hyatt-capital-gate.html",
    room: {
      title: "Deluxe King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
];
