import type { HotelProps } from "types/hotel";

export const hotels: HotelProps[] = [
  {
    id: "casa-lucia-buenos-aires",
    name: "Casa Lucia Member of Melia Collection",
    area: "Retiro",
    rating: { booking: 8.9, google: 4.6 },
    stars: 5,
    price: 5401,
    link: "https://www.booking.com/hotel/ar/casa-lucia-buenos-aires.html",
    room: {
      title: "Style Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "hub-portea-o",
    name: "Hub Porteño",
    area: "Recoleta",
    rating: { booking: 8.9, google: 4.5 },
    stars: 5,
    price: 4545,
    link: "https://www.booking.com/hotel/ar/hub-portea-o.html",
    room: {
      title: "Double or Twin Suite",
      sharing: true,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "sls-buenos-aires-puerto-madero",
    name: "SLS Buenos Aires Puerto Madero",
    area: "Puerto Madero",
    rating: { booking: 9, google: 4.5 },
    stars: 5,
    price: 6483,
    link: "https://www.booking.com/hotel/ar/sls-buenos-aires-puerto-madero.html",
    room: {
      title: "Superior King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "palladio-buenos-aires-mgallery-by-sofitel",
    name: "Palladio Hotel Buenos Aires - MGallery Collection",
    area: "Recoleta",
    rating: { booking: 9.5, google: 4.8 },
    stars: 5,
    price: 5433,
    link: "https://www.booking.com/hotel/ar/palladio-buenos-aires-mgallery-by-sofitel.html",
    room: {
      title: "Superior King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "melia-recoleta-plaza-boutique",
    name: "Melia Recoleta Plaza Hotel",
    area: "Recoleta",
    rating: { booking: 8.7, google: 4.4 },
    stars: 5,
    price: 5490,
    link: "https://www.booking.com/hotel/ar/melia-recoleta-plaza-boutique.html",
    room: {
      title: "Melia Room",
      sharing: true,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
    note: "20% off food/drink.",
  },
  {
    id: "hilton-buenos-aires",
    name: "Hilton Buenos Airesl",
    area: "Puerto Madero",
    rating: { booking: 9, google: 4.6 },
    stars: 5,
    price: 4077,
    link: "https://www.booking.com/hotel/ar/hilton-buenos-aires.html",
    room: {
      title: "Deluxe King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "aq-tailored-suites",
    name: "AQ Tailored Suites",
    area: "Recoleta",
    rating: { booking: 9, google: 4.6 },
    stars: 4,
    price: 5046,
    link: "https://www.booking.com/hotel/ar/aq-tailored-suites.html",
    room: {
      title: "Deluxe Double Room",
      sharing: true,
      bed: {
        total: 2,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "intercontinental-buenos-aires",
    name: "InterContinental Buenos Aires by IHG",
    area: "Monserrat",
    rating: { booking: 8.9, google: 4.6 },
    stars: 5,
    price: 4368,
    link: "https://www.booking.com/hotel/ar/intercontinental-buenos-aires.html",
    room: {
      title: "Classic King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "panamericano-buenos-aires",
    name: "Marriott Buenos Aires Downtown",
    area: "Downtown Buenos Aires",
    rating: { booking: 8.9, google: 4.5 },
    stars: 5,
    price: 4475,
    link: "https://www.booking.com/hotel/ar/panamericano-buenos-aires.html",
    room: {
      title: "Classic King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
];
