import type { HotelProps } from "types/hotel";

export const hotels: HotelProps[] = [
  {
    id: "melia-desert-palm-member-of-melia-collection",
    name: "Melia Desert Palm Member of Melia Collection",
    area: "International City",
    rating: { booking: 9.3, google: 4.6 },
    stars: 5,
    price: 6147,
    link: "https://www.booking.com/hotel/ae/melia-desert-palm-member-of-melia-collection.html",
    room: {
      title: "Palm Deluxe Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "grand-cosmopolitan-dubai",
    name: "Grand Cosmopolitan Hotel",
    area: "Al Barsha",
    rating: { booking: 9.3, google: 4.7 },
    stars: 5,
    price: 2880,
    link: "https://www.booking.com/hotel/ae/grand-cosmopolitan-dubai.html",
    room: {
      title: "Premium Room",
      sharing: true,
      bed: {
        total: 2,
        type: "King",
      },
    },
    breakfast: true,
    dinner: true,
  },
  {
    id: "one-amp-only-one-za-39-abeel",
    name: "One&Only One Za'abeel",
    area: "Trade Center Area",
    rating: { booking: 9, google: 4.7 },
    stars: 5,
    price: 7213,
    link: "https://www.booking.com/hotel/ae/one-amp-only-one-za-39-abeel.html",
    room: {
      title: "Zaabeel Room King",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    note: "Sheikh Zayed Road.",
  },

  {
    id: "damac-maison-aykon-city-dubai",
    name: "DAMAC Maison Aykon City Dubai",
    area: "Sheikh Zayed Road",
    rating: { booking: 9, google: 4.6 },
    stars: 4,
    price: 3727,
    link: "https://www.booking.com/hotel/ae/damac-maison-aykon-city-dubai.html",
    room: {
      title: "Studio City View",
      sharing: true,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: false,
    dinner: true,
    note: "With Kitchenette.",
  },
  {
    id: "wyndham-dubai-marina",
    name: "The First Collection Marina, Dubai, a Tribute Portfolio Hotel",
    area: "Dubai Marina",
    rating: { booking: 8.8, google: 4.4 },
    stars: 4,
    price: 2759,
    link: "https://www.booking.com/hotel/ae/wyndham-dubai-marina.html",
    room: {
      title: "Deluxe King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    note: "Sheikh Zayed Road.",
  },
  {
    id: "me-dubai",
    name: "ME Dubai by Meliá",
    area: "Business Bay",
    rating: { booking: 8.8, google: 4.3 },
    stars: 5,
    price: 5758,
    link: "https://www.booking.com/hotel/ae/me-dubai.html",
    room: {
      title: "Deluxe Always ME",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    dinner: true,
  },
  {
    id: "media-one",
    name: "Media One Hotel",
    area: "Dubai Media City",
    rating: { booking: 8.8, google: 4.3 },
    stars: 4,
    price: 2103,
    link: "https://www.booking.com/hotel/ae/media-one.html",
    room: {
      title: "Standard Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "local-at-jumeirah-village-triangle-by-the-first-collection",
    name: "Hotel Local Dubai, Jumeirah Village Triangle, Autograph Collection",
    rating: { booking: 8.8, google: 4.6 },
    stars: 4,
    price: 3238,
    link: "https://www.booking.com/hotel/ae/local-at-jumeirah-village-triangle-by-the-first-collection.html",
    room: {
      title: "Standard Double Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    note: "Private Beach.",
  },
  {
    id: "andaz-dubai-the-palm",
    name: "Andaz Dubai The Palm, By Hyatt",
    area: "Palm Jumeirah",
    rating: { booking: 8.8, google: 4.5 },
    stars: 5,
    price: 3048,
    link: "https://www.booking.com/hotel/ae/andaz-dubai-the-palm.html",
    room: {
      title: "King Room",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    note: "Private Beach.",
  },
];
