import type { HotelProps } from "types/hotel";

export const hotels: HotelProps[] = [
  {
    id: "park-hyatt-mendoza-casino-spa",
    name: "Park Hyatt Mendoza Hotel, Casino & Spa",
    area: "Mendoza City Center",
    rating: { booking: 8.9, google: 4.6 },
    stars: 5,
    price: 3569,
    link: "https://www.booking.com/hotel/ar/park-hyatt-mendoza-casino-spa.html",
    room: {
      title: "King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "sheraton-mendoza",
    name: "Sheraton Mendoza Hotel",
    area: "Mendoza City Center",
    rating: { booking: 8.8, google: 4.5 },
    stars: 4,
    price: 3235,
    link: "https://www.booking.com/hotel/ar/sheraton-mendoza.html",
    room: {
      title: "Guest King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "sheraton-mendoza",
    name: "Diplomatic Hotel",
    area: "Mendoza City Center",
    rating: { booking: 9.1, google: 4.6 },
    stars: 5,
    price: 3967,
    link: "https://www.booking.com/hotel/ar/sheraton-mendoza.html",
    room: {
      title: "Standard Double Room",
      sharing: true,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "hilton-mendoza",
    name: "Hilton Mendoza",
    rating: { booking: 8.7, google: 4.6 },
    stars: 5,
    price: 2907,
    link: "https://www.booking.com/hotel/ar/hilton-mendoza.html",
    room: {
      title: "King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "hilton-mendoza2",
    name: "Hilton Mendoza 2",
    rating: { booking: 8.7, google: 4.6 },
    stars: 5,
    price: 2907,
    link: "https://www.booking.com/hotel/ar/hilton-mendoza.html",
    room: {
      title: "Double Room",
      sharing: true,
      bed: {
        total: 2,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "huentala-boutique",
    name: "Huentala Hotel",
    area: "Mendoza City Center",
    rating: { booking: 8.7, google: 4.3 },
    stars: 4,
    price: 2261,
    link: "https://www.booking.com/hotel/ar/huentala-boutique.html",
    room: {
      title: "Classic Double Room",
      sharing: true,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "el-portal-plaza-suites",
    name: "Portal Plaza Suites",
    area: "Mendoza City Center",
    rating: { booking: 8.7, google: 4.4 },
    stars: 4,
    price: 1857,
    link: "https://www.booking.com/hotel/ar/el-portal-plaza-suites.html",
    room: {
      title: "Executive Double Room",
      sharing: true,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "mendoza-curio-collection-by-hilton",
    name: "Hualta Hotel Mendoza, Curio Collection by Hilton",
    area: "Mendoza City Center",
    rating: { booking: 8.7, google: 4.6 },
    stars: 4,
    price: 2907,
    link: "https://www.booking.com/hotel/ar/mendoza-curio-collection-by-hilton.html",
    room: {
      title: "King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "gran-dakar",
    name: "Gran Hotel Dakar",
    area: "Mendoza City Center",
    rating: { booking: 8.4, google: 4.2 },
    stars: 4,
    price: 2180,
    link: "https://www.booking.com/hotel/ar/gran-dakar.html",
    room: {
      title: "Superior Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "nh-cordillera",
    name: "NH Mendoza Cordillera",
    area: "Mendoza City Center",
    rating: { booking: 8.1, google: 4.2 },
    stars: 4,
    price: 2226,
    link: "https://www.booking.com/hotel/ar/nh-cordillera.html",
    room: {
      title: "Superior Double Room",
      sharing: true,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
];
