import type { HotelProps } from "types/hotel";

export const hotels: HotelProps[] = [
  {
    id: "hilton-barra-rio-de-janeiro",
    name: "Hilton Barra Rio de Janeiro",
    area: "Barra da Tijuca",
    rating: { booking: 9.1, google: 4.7 },
    stars: 4,
    price: 1969,
    link: "https://www.booking.com/hotel/br/hilton-barra-rio-de-janeiro.html",
    room: {
      title: "Superior King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "windsor-miramar",
    name: "Miramar By Windsor Copacabana",
    area: "Copacabana",
    rating: { booking: 9, google: 4.6 },
    stars: 5,
    price: 3330,
    link: "https://www.booking.com/hotel/br/windsor-miramar.html",
    room: {
      title: "Standard Double Room - No View",
      sharing: false,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "santa-teresa",
    name: "Santa Teresa Hotel Rio de Janeiro - MGallery Collection",
    area: "Santa Teresa",
    rating: { booking: 9.1, google: 4.7 },
    stars: 5,
    price: 11878,
    link: "https://www.booking.com/hotel/br/santa-teresa.html",
    room: {
      title: "Superior King Room",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    dinner: true,
  },
  {
    id: "windsor-barra",
    name: "Windsor Barra Hotel",
    area: "Barra da Tijuca",
    rating: { booking: 8.8, google: 4.7 },
    stars: 5,
    price: 2210,
    link: "https://www.booking.com/hotel/br/windsor-barra.html",
    room: {
      title: "Superior Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "windsor-marapendi",
    name: "Windsor Marapendi Hotel",
    area: "Barra da Tijuca",
    rating: { booking: 8.8, google: 4.7 },
    stars: 5,
    price: 2210,
    link: "https://www.booking.com/hotel/br/windsor-marapendi.html",
    room: {
      title: "Superior Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "vila-santa-teresa",
    name: "Vila Santa Teresa",
    area: "Santa Teresa",
    rating: { booking: 9.6, google: 4.9 },
    stars: 5,
    price: 10652,
    link: "https://www.booking.com/hotel/br/vila-santa-teresa.html",
    room: {
      title: "Suite with Garden View",
      sharing: true,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "brisa-barra",
    name: "Riale Brisa Barra",
    area: "Barra da Tijuca",
    rating: { booking: 8.6, google: 4.5 },
    stars: 4,
    price: 2291,
    link: "https://www.booking.com/hotel/br/brisa-barra.html",
    room: {
      title: "Quarto Superior",
      sharing: false,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "villa-paranagua",
    name: "Villa Paranaguá Hotel & Spa - Boutique Hotel",
    area: "Santa Teresa",
    rating: { booking: 9.5, google: 4.8 },
    stars: 5,
    price: 5959,
    link: "https://www.booking.com/hotel/br/villa-paranagua.html",
    room: {
      title: "Standard Suite",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "rio-de-janeiro",
    name: "Fairmont Rio de Janeiro Copacabana",
    area: "Copacabana",
    rating: { booking: 8.5, google: 4.7 },
    stars: 5,
    price: 6326,
    link: "https://www.booking.com/hotel/br/rio-de-janeiro.html",
    room: {
      title: "Fairmont King Room with City View",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "hilton-copabacana",
    name: "Hilton Copacabana Rio de Janeiro",
    area: "Copacabana",
    rating: { booking: 8.4, google: 4.6 },
    stars: 5,
    price: 3150,
    link: "https://www.booking.com/hotel/br/hilton-copabacana.html",
    room: {
      title: "King Room with City View",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "regente-rio-de-janeiro",
    name: "Grand Mercure Rio de Janeiro Copacabana",
    area: "Copacabana",
    rating: { booking: 8.3, google: 4.3 },
    stars: 4,
    price: 2744,
    link: "https://www.booking.com/hotel/br/regente-rio-de-janeiro.html",
    room: {
      title: "Classic Queen Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "yoo2-botafogo",
    name: "Yoo2 Rio de Janeiro, Tapestry Collection by Hilton",
    area: "Botafogo",
    rating: { booking: 8.3, google: 4.5 },
    stars: 5,
    price: 4352,
    link: "https://www.booking.com/hotel/br/yoo2-botafogo.html",
    room: {
      title: "Quarto Standard com Cama King",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "radisson-rio-de-janeiro-barra",
    name: "Radisson Rio de Janeiro Barra",
    area: "Barra da Tijuca",
    rating: { booking: 8.2, google: 4.5 },
    stars: 4,
    price: 2905,
    link: "https://www.booking.com/hotel/br/radisson-rio-de-janeiro-barra.html",
    room: {
      title: "Superior King Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
    dinner: true,
  },
];
