import type { HotelProps } from "types/hotel";

export const hotels: HotelProps[] = [
  {
    id: "magnolia",
    name: "Hotel Magnolia Santiago",
    area: "Downtown Santiago",
    rating: { booking: 9.1, google: 4.6 },
    stars: 4,
    price: 5684,
    link: "https://www.booking.com/hotel/cl/magnolia.html",
    room: {
      title: "Superior Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    dinner: true,
  },
  {
    id: "cumbres-lastarria",
    name: "Hotel Cumbres Lastarria",
    area: "Downtown Santiago",
    rating: { booking: 9, google: 4.6 },
    stars: 4,
    price: 3052,
    link: "https://www.booking.com/hotel/cl/cumbres-lastarria.html",
    room: {
      title: "Standard Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "the-singular-santiago",
    name: "The Singular Santiago",
    area: "Downtown Santiago",
    rating: { booking: 9.3, google: 4.7 },
    stars: 5,
    price: 3875,
    link: "https://www.booking.com/hotel/cl/the-singular-santiago.html",
    room: {
      title: "Standard Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "solace-santiago",
    name: "Solace Hotel Santiago",
    area: "Providencia",
    rating: { booking: 8.8, google: 4.6 },
    stars: 4,
    price: 3052,
    link: "https://www.booking.com/hotel/cl/solace-santiago.html",
    room: {
      title: "Superior King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "lq-by-la-quinta-santiago-aeropuerto",
    name: "Wyndham Santiago Aeropuerto",
    area: "Pudahuel",
    rating: { booking: 8.9, google: 4.4 },
    stars: 4,
    price: 2180,
    link: "https://www.booking.com/hotel/cl/lq-by-la-quinta-santiago-aeropuerto.html",
    room: {
      title: "Queen Room",
      sharing: true,
      bed: {
        total: 2,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "hyatt-centric-las-condes-santiago",
    name: "Hyatt Centric Las Condes Santiago",
    area: "Las Condes",
    rating: { booking: 8.8, google: 4.7 },
    stars: 4,
    price: 2955,
    link: "https://www.booking.com/hotel/cl/hyatt-centric-las-condes-santiago.html",
    room: {
      title: "King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "nh-collection-plaza-santiago",
    name: "NH Collection Plaza Santiago",
    area: "Las Condes",
    rating: { booking: 8.6, google: 4.5 },
    stars: 5,
    price: 2908,
    link: "https://www.booking.com/hotel/cl/nh-collection-plaza-santiago.html",
    room: {
      title: "Superior Double Room",
      sharing: true,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: false,
  },
  {
    id: "plaza-san-francisco",
    name: "Hotel Plaza San Francisco",
    area: "Downtown Santiago",
    rating: { booking: 8.9, google: 4.6 },
    stars: 5,
    price: 2729,
    link: "https://www.booking.com/hotel/cl/plaza-san-francisco.html",
    room: {
      title: "Standard King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
    note: "20% off food/drink.",
  },
  {
    id: "debaines-santiago",
    name: "Debaines Hotel Santiago",
    area: "Downtown Santiago",
    rating: { booking: 8.3, google: 4.6 },
    stars: 5,
    price: 4461,
    link: "https://www.booking.com/hotel/cl/debaines-santiago.html",
    room: {
      title: "Superior King Room",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
    lunch: true,
  },
];
