import type { HotelProps } from "types/hotel";

export const hotels: HotelProps[] = [
  {
    id: "grand-hyatt-sao-paulo",
    name: "Grand Hyatt São Paulo",
    area: "Itaim Bibi District",
    rating: { booking: 9, google: 4.7 },
    stars: 5,
    price: 3482,
    link: "https://www.booking.com/hotel/br/grand-hyatt-sao-paulo.html",
    room: {
      title: "Queen Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "qoya-sao-paulo-curio-collection-by-hilton",
    name: "Qoya São Paulo Paulista, Curio Collection by Hilton",
    area: "Vila Mariana",
    rating: { booking: 8.9, google: 4.5 },
    stars: 4,
    price: 3133,
    link: "https://www.booking.com/hotel/br/qoya-sao-paulo-curio-collection-by-hilton.html",
    room: {
      title: "Double Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "rosewood-sao-paulo",
    name: "Rosewood São Paulo",
    area: "Bela Vista",
    rating: { booking: 9.5, google: 4.8 },
    stars: 5,
    price: 13228,
    link: "https://www.booking.com/hotel/br/rosewood-sao-paulo.html",
    room: {
      title: "King Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "porto-bay-lhotel",
    name: "L'Hotel PortoBay São Paulo",
    area: "Bela Vista",
    rating: { booking: 9.3, google: 4.6 },
    stars: 5,
    price: 6142,
    link: "https://www.booking.com/hotel/br/porto-bay-lhotel.html",
    room: {
      title: "Executive Double Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: false,
  },
  {
    id: "porto-bay-lhotel",
    name: "Canopy By Hilton Sao Paulo Jardins",
    area: "Jardim Paulista",
    rating: { booking: 8.8, google: 4.6 },
    stars: 5,
    price: 3530,
    link: "https://www.booking.com/hotel/br/porto-bay-lhotel.html",
    room: {
      title: "Standard King Room",
      sharing: false,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "melia-jardim-europa",
    name: "Meliá Jardim Europa",
    area: "Itaim Bibi District",
    rating: { booking: 8.8, google: 4.5 },
    stars: 5,
    price: 3157,
    link: "https://www.booking.com/hotel/br/melia-jardim-europa.html",
    room: {
      title: "Deluxe King Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
  {
    id: "the-westin-sao-paulo",
    name: "The Westin Sao Paulo",
    area: "Itaim Bibi District",
    rating: { booking: 9.1, google: 4.6 },
    stars: 5,
    price: 6116,
    link: "https://www.booking.com/hotel/br/the-westin-sao-paulo.html",
    room: {
      title: "Deluxe Room",
      sharing: true,
      bed: {
        total: 2,
        type: "Double",
      },
    },
    breakfast: true,
  },
  {
    id: "tivolimoffarej",
    name: "Tivoli Mofarrej São Paulo Hotel",
    area: "Jardim Paulista",
    rating: { booking: 9, google: 4.7 },
    stars: 5,
    price: 8188,
    link: "https://www.booking.com/hotel/br/tivolimoffarej.html",
    room: {
      title: "Deluxe Room",
      sharing: true,
      bed: {
        total: 1,
        type: "King",
      },
    },
    breakfast: true,
  },
  {
    id: "radisson-paulista",
    name: "Radisson São Paulo Paulista",
    area: "Vila Mariana",
    rating: { booking: 8.1, google: 4.4 },
    stars: 4,
    price: 3369,
    link: "https://www.booking.com/hotel/br/radisson-paulista.html",
    room: {
      title: "Superior Queen Room",
      sharing: false,
      bed: {
        total: 1,
        type: "Queen",
      },
    },
    breakfast: true,
  },
];
